"""accounts: admins, registrations, login codes, sessions

Revision ID: 7f77ee4826d6
Revises: f82304bfef62
Create Date: 2026-09-24 19:53:53.292931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f77ee4826d6'
down_revision: Union[str, Sequence[str], None] = 'f82304bfef62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('trade', sa.Enum('maintenance', 'housekeeping', name='request_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins'))
    )
    op.create_table('login_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('app', sa.Enum('tenant', 'field', 'ops', 'housekeeping', name='app', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_codes'))
    )
    op.create_index('ix_login_codes_phone_app', 'login_codes', ['phone', 'app'], unique=False)
    op.create_table('tenant_registrations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('unit_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'declined', name='decision', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint("decision = 'approved' OR tenant_id IS NULL", name=op.f('ck_tenant_registrations_only_approved_have_a_tenant')),
    sa.CheckConstraint('(decision IS NULL) = (decided_at IS NULL)', name=op.f('ck_tenant_registrations_decision_and_time_together')),
    sa.ForeignKeyConstraint(['decided_by'], ['admins.id'], name=op.f('fk_tenant_registrations_decided_by_admins')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_registrations_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_tenant_registrations_unit_id_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_registrations'))
    )
    op.create_index(op.f('ix_tenant_registrations_unit_id'), 'tenant_registrations', ['unit_id'], unique=False)
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('app', sa.Enum('tenant', 'field', 'ops', 'housekeeping', name='app', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('registration_id', sa.String(length=32), nullable=True),
    sa.Column('staff_id', sa.String(length=64), nullable=True),
    sa.Column('admin_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_sessions_admin_id_admins'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['tenant_registrations.id'], name=op.f('fk_sessions_registration_id_tenant_registrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_sessions_staff_id_staff'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_sessions'))
    )
    op.alter_column('tenants', 'email',
               existing_type=sa.VARCHAR(length=254),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'email',
               existing_type=sa.VARCHAR(length=254),
               nullable=False)
    op.drop_table('sessions')
    op.drop_index(op.f('ix_tenant_registrations_unit_id'), table_name='tenant_registrations')
    op.drop_table('tenant_registrations')
    op.drop_index('ix_login_codes_phone_app', table_name='login_codes')
    op.drop_table('login_codes')
    op.drop_table('admins')
    # ### end Alembic commands ###
