"""retire staff and rates; order the rate card

Revision ID: f82304bfef62
Revises: fbe5e0b119e5
Create Date: 2026-09-23 22:51:15.174705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82304bfef62'
down_revision: Union[str, Sequence[str], None] = 'fbe5e0b119e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Added empty, filled for rates that already exist (their order was never
    # recorded, so by service type), then required: a NOT NULL column can't be
    # added to rows that have no value for it.
    op.add_column('housekeeping_rates', sa.Column('position', sa.Integer(), nullable=True))
    op.execute(
        "UPDATE housekeeping_rates SET position = ordered.n FROM "
        "(SELECT service_type, row_number() OVER (ORDER BY service_type) - 1 AS n "
        "FROM housekeeping_rates) AS ordered "
        "WHERE housekeeping_rates.service_type = ordered.service_type"
    )
    op.alter_column('housekeeping_rates', 'position', nullable=False)
    op.add_column('housekeeping_rates', sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_housekeeping_rates_position', 'housekeeping_rates', ['position'])
    op.add_column('staff', sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'retired_at')
    op.drop_constraint('uq_housekeeping_rates_position', 'housekeeping_rates', type_='unique')
    op.drop_column('housekeeping_rates', 'retired_at')
    op.drop_column('housekeeping_rates', 'position')
    # ### end Alembic commands ###
