"""initial tables

Revision ID: fbe5e0b119e5
Revises: 
Create Date: 2026-09-23 21:45:43.018910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbe5e0b119e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housekeeping_rates',
    sa.Column('service_type', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_housekeeping_rates_price_not_negative')),
    sa.PrimaryKeyConstraint('service_type', name=op.f('pk_housekeeping_rates'))
    )
    op.create_table('listings',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('area_sqft', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('slug', name=op.f('pk_listings'))
    )
    op.create_table('properties',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties'))
    )
    op.create_table('staff',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('maintenance', 'housekeeping', name='request_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff'))
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_table('units',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('property_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('occupied', 'under-maintenance', 'vacant', name='unit_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.CheckConstraint('bathrooms >= 0', name=op.f('ck_units_bathrooms_not_negative')),
    sa.CheckConstraint('bedrooms >= 0', name=op.f('ck_units_bedrooms_not_negative')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_units_property_id_properties')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_units_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('property_id', 'label', name='uq_units_property_id_label')
    )
    op.create_index(op.f('ix_units_property_id'), 'units', ['property_id'], unique=False)
    op.create_index(op.f('ix_units_tenant_id'), 'units', ['tenant_id'], unique=False)
    op.create_table('service_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('unit_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Enum('maintenance', 'housekeeping', name='request_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Enum('urgent', 'normal', name='priority', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assignee_id', sa.String(length=64), nullable=True),
    sa.Column('origin', sa.Enum('ops', 'tenant', name='origin', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('charge', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('schedule_date', sa.Date(), nullable=True),
    sa.Column('schedule_slot', sa.String(length=32), nullable=True),
    sa.Column('hand_back_reason', sa.Text(), nullable=True),
    sa.Column('hand_back_by', sa.String(length=64), nullable=True),
    sa.Column('hand_back_by_name', sa.String(length=200), nullable=True),
    sa.Column('hand_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type = 'housekeeping' OR category IN ('plumbing', 'electrical', 'ac', 'appliance', 'other')", name=op.f('ck_service_requests_maintenance_category_known')),
    sa.CheckConstraint("type = 'housekeeping' OR charge IS NULL", name=op.f('ck_service_requests_maintenance_is_not_charged')),
    sa.CheckConstraint("type = 'maintenance' OR priority = 'normal'", name=op.f('ck_service_requests_housekeeping_is_not_urgent')),
    sa.CheckConstraint('(hand_back_reason IS NULL) = (hand_back_at IS NULL)', name=op.f('ck_service_requests_hand_back_reason_and_time_together')),
    sa.CheckConstraint('(schedule_date IS NULL) = (schedule_slot IS NULL)', name=op.f('ck_service_requests_schedule_date_and_slot_together')),
    sa.CheckConstraint('charge IS NULL OR charge >= 0', name=op.f('ck_service_requests_charge_not_negative')),
    sa.ForeignKeyConstraint(['assignee_id'], ['staff.id'], name=op.f('fk_service_requests_assignee_id_staff')),
    sa.ForeignKeyConstraint(['hand_back_by'], ['staff.id'], name=op.f('fk_service_requests_hand_back_by_staff'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_service_requests_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_service_requests_unit_id_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_requests'))
    )
    op.create_index(op.f('ix_service_requests_assignee_id'), 'service_requests', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_service_requests_tenant_id'), 'service_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_service_requests_unit_id'), 'service_requests', ['unit_id'], unique=False)
    op.create_table('completion_photos',
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], name=op.f('fk_completion_photos_request_id_service_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', 'position', name=op.f('pk_completion_photos'))
    )
    op.create_table('photos',
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], name=op.f('fk_photos_request_id_service_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', 'position', name=op.f('pk_photos'))
    )
    op.create_table('stage_history',
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.Enum('submitted', 'assigned', 'in-progress', 'done', name='stage', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], name=op.f('fk_stage_history_request_id_service_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', 'stage', name=op.f('pk_stage_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_history')
    op.drop_table('photos')
    op.drop_table('completion_photos')
    op.drop_index(op.f('ix_service_requests_unit_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_tenant_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_assignee_id'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_index(op.f('ix_units_tenant_id'), table_name='units')
    op.drop_index(op.f('ix_units_property_id'), table_name='units')
    op.drop_table('units')
    op.drop_table('tenants')
    op.drop_table('staff')
    op.drop_table('properties')
    op.drop_table('listings')
    op.drop_table('housekeeping_rates')
    # ### end Alembic commands ###
